version: '3.8'

services:
  calculator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lead_calculator_app
    expose:
      - "80"
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
